### PR TITLE
add integration test and travisci config

### PR DESCRIPTION
**Pull request by aerickson**
Currently working in my repo. 

https://travis-ci.org/aerickson/clamp/branches

### CODE REVIEW

**Comment by rqelibari** [comment]
That is something we should've added long time ago. Thank you!

For later: We should also add the possibilities to update [`homebrew-clamp`](https://github.com/jide/homebrew-clamp) repo automatically on new releases in this branch.

**Comment by rqelibari** [comment]
Everything looks fine! Only one question remains: Is there any reason we would need a special config file for travis? A quick diff showed no real difference.

**Comment by aerickson** [comment]
> Everything looks fine! Only one question remains: Is there any reason we would need a special config file for travis? A quick diff showed no real difference.

The only change from a default config is that it uses port 8080. I was thinking that it would be required to work on Travis (the container we're using is running 10.13, so port 80 requires sudo) but it turns out sudo doesn't require a password on the image. 

So... we could get rid of it, but it's going to be handy for testing sudo-less operation next.

**Comment by rqelibari** [comment]
@aerickson What is the status here, can I merge this branch?

**Comment by aerickson** [comment]
Let's land https://github.com/jide/clamp/issues/41 first. That will allow me to not check in the additional config file in .travis.

**Comment by aerickson** [comment]
I've rebased this on master and removed the additional config file.

Ready to land if you're happy with things.

**Pull request merged**
